package com.movie.dao;

import com.movie.pojo.t1User;
import com.movie.pojo.t1UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface t1UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int deleteByExample(t1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int insert(t1User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int insertSelective(t1User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    List<t1User> selectByExample(t1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    t1User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int updateByExampleSelective(@Param("record") t1User record, @Param("example") t1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int updateByExample(@Param("record") t1User record, @Param("example") t1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int updateByPrimaryKeySelective(t1User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    int updateByPrimaryKey(t1User record);
}