package com.movie.pojo;

public class t1User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1_user.id
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1_user.nick_name
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    public t1User(Long id, String nickName) {
        this.id = id;
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    public t1User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1_user.id
     *
     * @return the value of t1_user.id
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1_user.id
     *
     * @param id the value for t1_user.id
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1_user.nick_name
     *
     * @return the value of t1_user.nick_name
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1_user.nick_name
     *
     * @param nickName the value for t1_user.nick_name
     *
     * @mbg.generated Sat May 18 23:44:46 CST 2024
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }
}