
### GET All address
GET http://localhost:8701/user/v1/address/getAll
Accept: application/json

### POST queryDetail
POST http://localhost:8701/user/v1/address/queryDetail
Content-Type: application/json

{
  "addressId": 123
}

### 通过gateway调用
POST http://localhost:8888/api/user/v1/address/queryDetail
Content-Type: application/json

{
  "addressId": 123
}

###
